version: '3.9'

services:
  pg:
    image: postgres
    restart: always
    environment:
      POSTGRES_DB: bitcoin
      POSTGRES_USER: user
      POSTGRES_PASSWORD: password
    ports:
      - "5432:5432"