name: CI/CD Tests

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  Test:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2

      - name: Login
        uses: docker/login-action@v2
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Build Docker Compose
        run: |
          docker compose -f docker-compose.yaml up --build -d

      - name: Run migrations
        run: |
          docker exec app_fastapi poetry run alembic upgrade head

      - name: Create test database
        run: |
          docker exec pg_db psql -U user -d postgres -c "CREATE DATABASE test_db;"

      - name: Run tests in the web container
        run: |
          docker exec app_fastapi poetry run pytest -v -s tests --disable-warnings

      - name: Tear down
        if: always()
        run: |
          docker compose -f docker-compose.yaml down